# Check out https://docs.codemagic.io/getting-started/building-a-react-native-app/ for more information
# Please review and update values in curly braces


workflows:
    react-native-android:
        name: Bloggero Android
        max_build_duration: 120
        instance_type: mac_mini
        environment:
            groups:
                - bloggero-app    
            vars:
                REACT_APP_GOOGLE_PLAYSTORE_REVENUECAT_KEY: Encrypted()
                PACKAGE_NAME: "com.bloggero"
            node: 16.14.0
        scripts:
            - name: Set up keystore
              script: | 
                echo $CM_KEYSTORE | base64 --decode > $CM_KEYSTORE_PATH/android/app
            - name: Install yarn dependencies
              script: | 
                yarn install
            - name: Set Android SDK location
              script: | 
                echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
            - name: Build Android release
              script: | 
                LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name '$PACKAGE_NAME')
                if [ -z LATEST_BUILD_NUMBER ]; then
                # fallback in case no build number was found from google play. Alternatively, you can `exit 1` to fail the build
                    UPDATED_BUILD_NUMBER=$BUILD_NUMBER
                else
                    UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
                fi
                cd android && ./gradlew bundleRelease -PversionCode=$UPDATED_BUILD_NUMBER -PversionName=1.0.$UPDATED_BUILD_NUMBER
            
            
        artifacts:
            - android/app/build/outputs/**/*.apk

        publishing:
            email:
                recipients:
                    - onaelmangabo@gmail.com
                notify:
                  success: true     # To not receive a notification when a build succeeds
                  failure: false    # To not receive a notification when a build fails
            google_play:
              credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
              track: internal
              submit_as_draft: true